### PR TITLE
ci: add post-commit hook with license header checks and linting

### PR DESCRIPTION
**Pull request by mipro98**
This adds a commit hook to prevent commiting files with wrong or missing license headers.

Can be installed with `setup_hooks.sh`. The core functionality is a python script `check_license_header.py`

TODO:
- [ ] enforce check also in CI (in case someone forgot to add the hook locally)
- [x] add functionality to the python script or another python script to auto-correct the files (either update the year or add the whole header) which can be executed manually (or maybe via a gradle task?)
- [x] Think about a better location than `.github` folder

### CODE REVIEW

**Comment by matthiasemde** [comment]
> * [ ]  enforce check also in CI (in case someone forgot to add the hook locally)

The problem with enforcing copyright headers in the CI is that there will always be exceptions to the rule (i.e. PlayerState.kt), which would be complicated to then get past the checks.

This is also the reason why I moved the pre-commit hook to a post-commit hook which just throws a warning and tells you to fix the copyright which you can then simply ignore if it doesn't apply. 🤷

**Comment by mipro98** [comment]
> > * [ ]   enforce check also in CI (in case someone forgot to add the hook locally)
> 
> The problem with enforcing copyright headers in the CI is that there will always be exceptions to the rule (i.e. PlayerState.kt), which would be complicated to then get past the checks.
> 
> This is also the reason why I moved the pre-commit hook to a post-commit hook which just throws a warning and tells you to fix the copyright which you can then simply ignore if it doesn't apply. 🤷

Is this message also displayed when commiting graphically in Android Studio?

**Comment by matthiasemde** [comment]
Yes and no, the message is displayed in the git console in Android studio which is normally quite hidden. However, when the hook fails, Android Studio shows a notification.

**Review by matthiasemde — APPROVED** [review]
LGTM 🔥

**Pull request merged**
