### PR TITLE
feat: add automatic license reports and license screen

### PR DESCRIPTION
**Pull request by matthiasemde**
Add 'com.jaredsburrows.license' dependency which includes gradle task 'licenseReleaseReport' for generating a report of all dependencies and their licenses.

Add tools/format_licenses.sh for converting the license report to a nicely formatted text.

Add LicenseScreen.kt to display the formatted license report.

Closes: #16

### CODE REVIEW

**Comment by mipro98** [comment]
Interesting, but how is it supposed to work? For me, it ends up in a screen like this after building:

<details>
<summary>Screenshot</summary>

image

</details>

Also, running `tools/format_licenses.sh` resultet in an error:
```
grep: app/build/reports/licenses/licenseReleaseReport.txt: No such file or directory
```

is the `format_licenses.sh` supposed to run automatically or somehow triggered via gradle?

Also, please make `format_licenses.sh` executable if it is supposed to be executed.

**Comment by matthiasemde** [comment]
> Interesting, but how is it supposed to work? For me, it ends up in a screen like this after building:
> Screenshot

Yes, that is exactly how it is supposed to work 👍 


> Also, running `tools/format_licenses.sh` resultet in an error:
> 
> ```
> grep: app/build/reports/licenses/licenseReleaseReport.txt: No such file or directory
> ```

Of course, you haven't run the 'licenseReleaseReport' task as mentioned in the PR. 👀 

> is the `format_licenses.sh` supposed to run automatically or somehow triggered via gradle?

No, this is the part about it being semi-automatic. 😅 

> Also, please make `format_licenses.sh` executable if it is supposed to be executed.

Windows... 😕

**Comment by mipro98** [comment]
> Of course, you haven't run the 'licenseReleaseReport' task as mentioned in the PR. 👀

How do I run it? Or is this supposed to only be triggered on a release in the CI?

**Comment by matthiasemde** [comment]
> How do I run it? Or is this supposed to only be triggered on a release in the CI?

You run it like any other gradle task: `./gradlew licenseReleaseReport`

**Review by mipro98 — APPROVED** [review]

**Pull request merged**
